// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpresaVideojuegos.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EmpresaVideojuegos.Modelos.Desarrolladora", b =>
                {
                    b.Property<int>("Id_desarrolladora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Año")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_desarrolladora");

                    b.ToTable("Desarrolladora");
                });

            modelBuilder.Entity("EmpresaVideojuegos.Modelos.Videojuego", b =>
                {
                    b.Property<int>("Id_videojuego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Año")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DesarrolladoraId_desarrolladora")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneroPrincipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("Id_videojuego");

                    b.HasIndex("DesarrolladoraId_desarrolladora");

                    b.ToTable("Videojuego");
                });

            modelBuilder.Entity("EmpresaVideojuegos.Modelos.Videojuego", b =>
                {
                    b.HasOne("EmpresaVideojuegos.Modelos.Desarrolladora", "Desarrolladora")
                        .WithMany("Videojuegos")
                        .HasForeignKey("DesarrolladoraId_desarrolladora");

                    b.Navigation("Desarrolladora");
                });

            modelBuilder.Entity("EmpresaVideojuegos.Modelos.Desarrolladora", b =>
                {
                    b.Navigation("Videojuegos");
                });
#pragma warning restore 612, 618
        }
    }
}
